# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/mindmap',
                'doc_host': 'https://arunslb123.github.io',
                'git_url': 'https://github.com/arunslb123/mindmap',
                'lib_path': 'mindmap'},
  'syms': {'mindmap.core': {'mindmap.core.foo': ('core.html#foo', 'mindmap/core.py')}}}
